### PR TITLE
Deploy with one command

### PR DESCRIPTION
**Pull request by kzadurska**
https://www.gatsbyjs.org/docs/how-gatsby-works-with-github-pages/#github-repository-page

It's alive!
https://kzadurska.github.io/expecto-frontendum/

### CODE REVIEW

**Comment by kzadurska** [comment]
@robertkirsz please approve :joy:

**Comment by robert-kirsz-kreditech** [comment]
I thought I did it already 🤔

**Comment by kzadurska** [comment]
Not this Robert XD

**Comment by robert-kirsz-kreditech** [comment]
Oh... Yeah... 🙃

**Pull request merged**
